Added microbenchmarks for profiling, correlating atomic performance on QV100
accel-sim/gpu-app-collection pull request #11
Opened 2022-03-31 01:55 UTC by abhaumick

- atomic_add_bw_conflict
    - added output dump to validate results
- atomic_add_bw_profile
    - some threads conflict on location 0
    - remaining threads access array[gid]
    - kernel arg ConflictCount for testing
- Updated app makefiles

2022-04-04 19:47 UTC, abhaumick commented
[7f3fd71](https://github.com/accel-sim/gpu-app-collection/pull/11/commits/7f3fd71cdf51cc8efd4e13932f80938c92b362c5) fixes Makefile issue causing Jenkins fail in [67c2a98](https://github.com/accel-sim/gpu-app-collection/pull/11/commits/67c2a98c69aad94c245c18e6a6578c6339884c13)

2022-04-04 21:07 UTC, FJShen requested changes
Please remove binary file src/cuda/GPU_Microbenchmark/Atomic_ubench/Atomic_add/Atomic_add_bw_profile/atomic_add_bw_profile away from the repository.

2022-04-04 21:07 UTC, FJShen commented on src/cuda/GPU_Microbenchmark/Atomic_ubench/Atomic_add/Atomic_add_bw/atomic_add_bw.cu
> +	printf("Found GPU Data Value = %d %d %d %d\n", data1[0], data1[1], data1[2], data1[3]);
For this and other *.cu files you commited - check if TOTAL_THREADS is greater than 4?

2022-04-04 21:07 UTC, FJShen commented on src/cuda/GPU_Microbenchmark/Atomic_ubench/Atomic_add/Atomic_add_bw_conflict/atomic_add_bw_conflict_profile.cu
> +		atomicAdd(&data1[atomic_loc], 10);
Where is atomic_loc declared? I don't see it in this *.cu file.

2022-04-05 22:45 UTC, abhaumick commented
> Please remove binary file src/cuda/GPU_Microbenchmark/Atomic_ubench/Atomic_add/Atomic_add_bw_profile/atomic_add_bw_profile away from the repository.

Done.

2022-04-05 22:54 UTC, abhaumick commented on src/cuda/GPU_Microbenchmark/Atomic_ubench/Atomic_add/Atomic_add_bw_conflict/atomic_add_bw_conflict_profile.cu
> +		atomicAdd(&data1[atomic_loc], 10);
Corrected this ..
Commented out by mistake

2022-04-05 23:11 UTC, abhaumick commented
Should not have made the original commit and PR in a hurry.
Mostly cleaned up .. hope no more stupid mistakes remain.

2022-04-05 23:20 UTC, abhaumick commented on src/cuda/GPU_Microbenchmark/Atomic_ubench/Atomic_add/Atomic_add_bw/atomic_add_bw.cu
> +	printf("Found GPU Data Value = %d %d %d %d\n", data1[0], data1[1], data1[2], data1[3]);
Checking the final values is tricky ...
It changes based on the ConflictCount and number of threads active.
I mostly printed it out to make sense in terms of order of magnitude  and by using a calculator (yeah .. sorry)
I can add more prints but unless someone is really digging into the values .. its not straightforward
But .. can be done I feel ..

2022-04-06 14:52 UTC, FJShen approved these changes

2022-04-13 23:13 UTC, barnes88 approved these changes

2022-04-13 23:14 UTC, merged