cutlass update
accel-sim/gpu-app-collection pull request #18
Opened 2023-07-17 17:10 UTC by Shreya-gaur

2023-07-20 04:48 UTC, JRPan requested changes
take out `.github` folder

2023-09-15 16:12 UTC, JRPan commented
@Shreya-gaur Could you please resolve the merge conflict? Thanks. I don't know why it's here again tho.

2024-01-28 15:01 UTC, tgrogers commented
@Shreya-gaur - can we change the way we integrate cutlass?
Instead of copying all the code here, can we just sync the folder to a particular commit number of their public repo?
We do something similar with heterosync:

https://github.com/accel-sim/gpu-app-collection/blob/52c11fbccbe11fefd8bb27c1ec64ecfd1828b088/src/Makefile#L304

We would still need your changes to Make, etc, but unless we are making changes to the cutlass code, I see no reason to duplicate it all here.

2024-02-07 17:28 UTC, JRPan approved these changes

2024-05-07 15:32 UTC, merged